from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setWindowTitle('MainWindow')
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(500, 300)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.groupNBP = QtWidgets.QGroupBox(self.centralwidget)
        self.groupNBP.setGeometry(QtCore.QRect(10, 10, 400, 160))
        self.groupNBP.setAlignment(QtCore.Qt.AlignCenter)
        self.groupNBP.setObjectName("groupBox")
        self.widget_2 = QtWidgets.QWidget(self.groupNBP)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 380, 80))
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        button_size_x = 120
        button_size_y = 30
        self.WybierzPlik_GUS = QtWidgets.QPushButton(self.widget_2)
        self.WybierzPlik_GUS.setGeometry(QtCore.QRect(110, 10, button_size_x, button_size_y))
        self.WybierzPlik_GUS.setObjectName("WybierzPlik_GUS")
        self.CreateXML_GUS = QtWidgets.QPushButton(self.widget_2)
        self.CreateXML_GUS.setGeometry(QtCore.QRect(235, 10, button_size_x, button_size_y))
        self.CreateXML_GUS.setObjectName("CreateXML_GUS")
        self.widget_3 = QtWidgets.QWidget(self.groupNBP)
        self.widget_3.setGeometry(QtCore.QRect(10, 60, 380, 80))
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.label_2.setObjectName("label_2")
        self.label_2.setWordWrap(True)
        self.SendToGus = QtWidgets.QPushButton(self.widget_3)
        self.SendToGus.setGeometry(QtCore.QRect(235, 10, button_size_x, button_size_y))
        self.SendToGus.setObjectName("SendToGus")
        self.WybierzPlik_GUS_2 = QtWidgets.QPushButton(self.widget_3)
        self.WybierzPlik_GUS_2.setGeometry(QtCore.QRect(110, 10, button_size_x, button_size_y))
        self.WybierzPlik_GUS_2.setObjectName("WybierzPlik_GUS_2")
        self.GUS_LOGIN = QtWidgets.QLineEdit(self.widget_3)
        drop = 60
        self.GUS_LOGIN.setGeometry(QtCore.QRect(0, drop, 113, 20))
        self.GUS_LOGIN.setObjectName("lineEdit")
        self.GUS_PWD = QtWidgets.QLineEdit(self.widget_3)
        self.GUS_PWD.setGeometry(QtCore.QRect(160, drop, 113, 20))
        self.GUS_PWD.setObjectName("GUS_PWD")
        self.groupNBP = QtWidgets.QGroupBox(self.centralwidget)
        self.groupNBP.setGeometry(QtCore.QRect(10, 180, 400, 80))
        self.groupNBP.setAlignment(QtCore.Qt.AlignCenter)
        self.groupNBP.setObjectName("groupNBP")
        self.widget = QtWidgets.QWidget(self.groupNBP)
        self.widget.setGeometry(QtCore.QRect(10, 15, 380, 80))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 120, 40))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.WybierzPlik_NBP = QtWidgets.QPushButton(self.widget)
        self.WybierzPlik_NBP.setGeometry(QtCore.QRect(110, 10, button_size_x, button_size_y))
        self.WybierzPlik_NBP.setObjectName("WybierzPlik_NBP")
        self.CreateXML_NBP = QtWidgets.QPushButton(self.widget)
        self.CreateXML_NBP.setGeometry(QtCore.QRect(235, 10, button_size_x, button_size_y))
        self.CreateXML_NBP.setObjectName("CreateXML_NBP")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupNBP.setTitle(_translate("MainWindow", "GUS"))
        self.label_4.setText(_translate("MainWindow", "Stwórz XML z tabeli Excel"))
        self.WybierzPlik_GUS.setText(_translate("MainWindow", "Wybierz Plik"))
        self.CreateXML_GUS.setText(_translate("MainWindow", "Stwórz XML"))
        self.label_2.setText(_translate("MainWindow", "Wyślij XML do GUS\'u"))
        self.SendToGus.setText(_translate("MainWindow", "Wyślij"))
        self.WybierzPlik_GUS_2.setText(_translate("MainWindow", "Wybierz Plik"))
        self.GUS_LOGIN.setText(_translate("MainWindow", "GUS-Login"))
        self.GUS_PWD.setText(_translate("MainWindow", "GUS-Hasło"))
        self.groupNBP.setTitle(_translate("MainWindow", "NBP"))
        self.label_3.setText(_translate("MainWindow", "Stwórz XML z tabeli Excel"))
        self.WybierzPlik_NBP.setText(_translate("MainWindow", "Wybierz Plik"))
        self.CreateXML_NBP.setText(_translate("MainWindow", "Stwórz XML"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())
