from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setWindowTitle('MainWindow')
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(450, 350)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 400, 170))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        button_size_x = 120
        button_size_y = 30

        self.sendToGUSwidget = QtWidgets.QWidget(self.groupBox)
        self.sendToGUSwidget.setGeometry(QtCore.QRect(10, 20, 380, 80))
        self.sendToGUSwidget.setObjectName("sendToGUSwidget")
        self.label_2 = QtWidgets.QLabel(self.sendToGUSwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 120, 40))
        self.label_2.setObjectName("label_2")
        self.label_2.setWordWrap(True)
        self.SendToGus = QtWidgets.QPushButton(self.sendToGUSwidget)
        self.SendToGus.setGeometry(QtCore.QRect(260, 0, button_size_x, button_size_y))
        self.SendToGus.setObjectName("SendToGus")
        self.WybierzPlik_GUS_ToSend = QtWidgets.QPushButton(self.sendToGUSwidget)
        self.WybierzPlik_GUS_ToSend.setGeometry(QtCore.QRect(120, 0, button_size_x, button_size_y))
        self.WybierzPlik_GUS_ToSend.setObjectName("WybierzPlik_GUS_ToSend")
        self.GUS_LOGIN = QtWidgets.QLineEdit(self.sendToGUSwidget)
        self.GUS_LOGIN.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.GUS_LOGIN.setObjectName("GUS_LOGIN")
        self.GUS_PWD = QtWidgets.QLineEdit(self.sendToGUSwidget)
        self.GUS_PWD.setGeometry(QtCore.QRect(260, 40, 113, 20))
        self.GUS_PWD.setObjectName("GUS_PWD")
        self.GUS_Form_Send = QtWidgets.QComboBox(self.sendToGUSwidget)
        self.GUS_Form_Send.setGeometry(QtCore.QRect(0, 40, 100, 22))
        self.GUS_Form_Send.setObjectName("GUS_Form_Send")
        self.GUS_Form_Send.addItem("")
        self.GUS_Form_Send.addItem("")
        self.GUS_Form_Send.addItem("")
        self.GUS_Form_Send.addItem("")
        self.GUS_Form_Send.addItem("")
        self.GUS_Form_Send.addItem("")

        self.CreateXML_GUS = QtWidgets.QWidget(self.groupBox)
        self.CreateXML_GUS.setGeometry(QtCore.QRect(10, 90, 380, 160))
        self.CreateXML_GUS.setObjectName("CreateXML_GUS")
        self.label_4 = QtWidgets.QLabel(self.CreateXML_GUS)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.createXML_1 = QtWidgets.QWidget(self.CreateXML_GUS)
        self.createXML_1.setGeometry(QtCore.QRect(120, 10, 300, 61))
        self.createXML_1.setObjectName("createXML_1")
        self.GUS_Form_to_XML = QtWidgets.QComboBox(self.createXML_1)
        self.GUS_Form_to_XML.setGeometry(QtCore.QRect(0, 0, 100, 22))
        self.GUS_Form_to_XML.setObjectName("GUS_Form_to_XML")
        self.GUS_Form_to_XML.addItem("C-01")
        self.GUS_Form_to_XML.addItem("DG-1")
        self.GUS_Form_to_XML.addItem("DNU-K")
        self.GUS_Form_to_XML.addItem("F-01")
        self.GUS_Form_to_XML.addItem("GP")
        self.GUS_Form_to_XML.addItem("SP")
        self.GUS_sheetname = QtWidgets.QLineEdit(self.createXML_1)
        self.GUS_sheetname.setGeometry(QtCore.QRect(140, 0, 81, 21))
        self.GUS_sheetname.setObjectName("GUS_sheetname")
        self.CreateXML_GUS = QtWidgets.QPushButton(self.createXML_1)
        self.CreateXML_GUS.setGeometry(QtCore.QRect(140, 30, button_size_x, button_size_y))
        self.CreateXML_GUS.setObjectName("CreateXML_GUS")
        self.WybierzPlikGUS_ToXML = QtWidgets.QPushButton(self.createXML_1)
        self.WybierzPlikGUS_ToXML.setGeometry(QtCore.QRect(0, 30, button_size_x, button_size_y))
        self.WybierzPlikGUS_ToXML.setObjectName("WybierzPlikGUS_ToXML")
        
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 400, 120))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.createXML_NBP = QtWidgets.QWidget(self.groupBox_2)
        self.createXML_NBP.setGeometry(QtCore.QRect(10, 20, 380, 80))
        self.createXML_NBP.setObjectName("createXML_NBP")
        self.label_3 = QtWidgets.QLabel(self.createXML_NBP)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 120, 40))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.createXML_2 = QtWidgets.QWidget(self.createXML_NBP)
        self.createXML_2.setGeometry(QtCore.QRect(120, 10, 380, 80))
        self.createXML_2.setObjectName("createXML_2")
        self.NBPForm = QtWidgets.QComboBox(self.createXML_2)
        self.NBPForm.setGeometry(QtCore.QRect(0, 0, 100, 22))
        self.NBPForm.setObjectName("NBPForm")
        self.NBPForm.addItem("C-01")
        self.NBPForm.addItem("DG-1")
        self.NBPForm.addItem("DNU-K")
        self.NBPForm.addItem("F-01")
        self.NBPForm.addItem("GP")
        self.NBPForm.addItem("SP")
        self.NBP_sheetname = QtWidgets.QLineEdit(self.createXML_2)
        self.NBP_sheetname.setGeometry(QtCore.QRect(140, 0, 81, 21))
        self.NBP_sheetname.setObjectName("NBP_sheetname")
        self.CreateXML_NBP = QtWidgets.QPushButton(self.createXML_2)
        self.CreateXML_NBP.setGeometry(QtCore.QRect(140, 30, button_size_x, button_size_y))
        self.CreateXML_NBP.setObjectName("CreateXML_NBP")
        self.WybierzPlik_NBP = QtWidgets.QPushButton(self.createXML_2)
        self.WybierzPlik_NBP.setGeometry(QtCore.QRect(0, 30, button_size_x, button_size_y))
        self.WybierzPlik_NBP.setObjectName("WybierzPlik_NBP")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Scripts"))
        self.groupBox.setTitle(_translate("MainWindow", "GUS"))
        self.label_4.setText(_translate("MainWindow", "Stwórz XML z tabeli Excel"))
        self.GUS_Form_to_XML.setItemText(0, _translate("MainWindow", "C-01"))
        self.GUS_Form_to_XML.setItemText(1, _translate("MainWindow", "DG-1"))
        self.GUS_Form_to_XML.setItemText(2, _translate("MainWindow", "DNU-K"))
        self.GUS_Form_to_XML.setItemText(3, _translate("MainWindow", "F-01"))
        self.GUS_Form_to_XML.setItemText(4, _translate("MainWindow", "GP"))
        self.GUS_Form_to_XML.setItemText(5, _translate("MainWindow", "SP"))
        self.GUS_sheetname.setText(_translate("MainWindow", "Arkusz1"))
        self.CreateXML_GUS.setText(_translate("MainWindow", "Stwórz XML"))
        self.WybierzPlikGUS_ToXML.setText(_translate("MainWindow", "Wybierz Plik"))
        self.label_2.setText(_translate("MainWindow", "Wyślij XML do GUS\'u"))
        self.SendToGus.setText(_translate("MainWindow", "Wyślij"))
        self.WybierzPlik_GUS_ToSend.setText(_translate("MainWindow", "Wybierz Plik"))
        self.GUS_LOGIN.setText(_translate("MainWindow", "GUS-Login"))
        self.GUS_PWD.setText(_translate("MainWindow", "GUS-Hasło"))
        self.GUS_Form_Send.setItemText(0, _translate("MainWindow", "C-01"))
        self.GUS_Form_Send.setItemText(1, _translate("MainWindow", "DG-1"))
        self.GUS_Form_Send.setItemText(2, _translate("MainWindow", "DNU-K"))
        self.GUS_Form_Send.setItemText(3, _translate("MainWindow", "F-01"))
        self.GUS_Form_Send.setItemText(4, _translate("MainWindow", "GP"))
        self.GUS_Form_Send.setItemText(5, _translate("MainWindow", "SP"))
        self.groupBox_2.setTitle(_translate("MainWindow", "NBP"))
        self.label_3.setText(_translate("MainWindow", "Stwórz XML z tabeli Excel"))
        self.NBPForm.setItemText(0, _translate("MainWindow", "C-01"))
        self.NBPForm.setItemText(1, _translate("MainWindow", "DG-1"))
        self.NBPForm.setItemText(2, _translate("MainWindow", "DNU-K"))
        self.NBPForm.setItemText(3, _translate("MainWindow", "F-01"))
        self.NBPForm.setItemText(4, _translate("MainWindow", "GP"))
        self.NBPForm.setItemText(5, _translate("MainWindow", "SP"))
        self.NBP_sheetname.setText(_translate("MainWindow", "Arkusz1"))
        self.CreateXML_NBP.setText(_translate("MainWindow", "Stwórz XML"))
        self.WybierzPlik_NBP.setText(_translate("MainWindow", "Wybierz Plik"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())
