from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setWindowTitle('MainWindow')
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)

        # NBP field
        self.NBP_XML_Form = QtWidgets.QGroupBox()
        self.NBP_XML_Form.setGeometry(QtCore.QRect(0, 330, 500, 220))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.NBP_XML_Form.setFont(font)
        self.NBP_XML_Form.setAlignment(QtCore.Qt.AlignCenter)
        self.choises_1 = QtWidgets.QWidget(self.NBP_XML_Form)
        self.choises_1.setGeometry(QtCore.QRect(0, 10, 330, 211))
        self.NBP_ChooseFile = QtWidgets.QPushButton(self.choises_1)
        self.NBP_ChooseFile.setGeometry(QtCore.QRect(185, 90, 120, 30))
        self.NBP_ChooseFile.setFont(font)
        self.choose_NBP_XML = QtWidgets.QComboBox(self.choises_1)
        self.choose_NBP_XML.setGeometry(QtCore.QRect(185, 30, 120, 30))
        self.choose_NBP_XML.setFont(font)
        self.choose_NBP_XML.addItem("")
        self.choose_NBP_XML.addItem("")
        self.choose_NBP_XML.addItem("")
        self.choose_NBP_XML.addItem("")
        self.choose_NBP_XML.addItem("")
        self.choose_NBP_XML.addItem("")
        self.choose_NBP_XML.addItem("")
        self.label_1 = QtWidgets.QLabel(self.choises_1)
        self.label_1.setGeometry(QtCore.QRect(30, 30, 120, 30))
        self.label_1.setFont(font)
        self.label_2 = QtWidgets.QLabel(self.choises_1)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 120, 30))
        self.label_2.setFont(font)
        self.label_3 = QtWidgets.QLabel(self.choises_1)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 140, 30))
        self.NBP_SheetName = QtWidgets.QPlainTextEdit(self.choises_1)
        self.NBP_SheetName.setGeometry(QtCore.QRect(185, 150, 120, 30))
        self.NBP_SheetName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.NBP_SheetName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.NBP_SheetName.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.NBP_SheetName.setReadOnly(False)
        self.NBP_CreateButton = QtWidgets.QPushButton(self.NBP_XML_Form)
        self.NBP_CreateButton.setGeometry(QtCore.QRect(360, 90, 120, 50))
        self.NBP_CreateButton.setFont(font)
        self.setCentralWidget(self.NBP_XML_Form)
        
        # GUS_field
        self.GUS_XML_Form = QtWidgets.QGroupBox()
        self.GUS_XML_Form.setGeometry(QtCore.QRect(300, 330, 500, 220))
        self.GUS_XML_Form.setFont(font)
        self.GUS_XML_Form.setAlignment(QtCore.Qt.AlignCenter)
        self.choises_1 = QtWidgets.QWidget(self.GUS_XML_Form)
        self.choises_1.setGeometry(QtCore.QRect(0, 10, 330, 211))
        self.GUS_ChooseFile = QtWidgets.QPushButton(self.choises_1)
        self.GUS_ChooseFile.setGeometry(QtCore.QRect(185, 90, 120, 30))
        self.GUS_ChooseFile.setFont(font)
        self.choose_GUS_XML = QtWidgets.QComboBox(self.choises_1)
        self.choose_GUS_XML.setGeometry(QtCore.QRect(185, 30, 120, 30))
        self.choose_GUS_XML.setFont(font)
        self.choose_GUS_XML.addItem("")
        self.choose_GUS_XML.addItem("")
        self.choose_GUS_XML.addItem("")
        self.choose_GUS_XML.addItem("")
        self.choose_GUS_XML.addItem("")
        self.choose_GUS_XML.addItem("")
        self.choose_GUS_XML.addItem("")
        self.label_1 = QtWidgets.QLabel(self.choises_1)
        self.label_1.setGeometry(QtCore.QRect(30, 30, 120, 30))
        self.label_1.setFont(font)
        self.label_2 = QtWidgets.QLabel(self.choises_1)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 120, 30))
        self.label_2.setFont(font)
        self.label_3 = QtWidgets.QLabel(self.choises_1)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 140, 30))
        self.GUS_SheetName = QtWidgets.QPlainTextEdit(self.choises_1)
        self.GUS_SheetName.setGeometry(QtCore.QRect(185, 150, 120, 30))
        self.GUS_SheetName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GUS_SheetName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GUS_SheetName.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.GUS_SheetName.setReadOnly(False)
        self.GUS_CreateButton = QtWidgets.QPushButton(self.GUS_XML_Form)
        self.GUS_CreateButton.setGeometry(QtCore.QRect(360, 90, 120, 50))
        self.GUS_CreateButton.setFont(font)
        self.setCentralWidget(self.GUS_XML_Form)

        # menu
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.setStatusBar(self.statusbar)
        self.actionAdd_file = QtWidgets.QAction(self)
        self.actionAdd_file.setText("Add File")
        self.actionAdd_file.setStatusTip("")
        self.actionAdd_file.setAutoRepeat(True)
        self.actionSort_Values = QtWidgets.QAction(self)
        self.actionEmail = QtWidgets.QAction(self)
        self.menuFiles.addAction(self.actionAdd_file)
        self.menuActions.addAction(self.actionSort_Values)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuHome.menuAction())
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NBP_XML_Form.setTitle(_translate("MainWindow", "NBP XMLs"))
        self.NBP_ChooseFile.setText(_translate("MainWindow", "Choose File"))
        self.choose_NBP_XML.setItemText(0, _translate("MainWindow", "MAZ-DEP"))
        self.choose_NBP_XML.setItemText(1, _translate("MainWindow", "MAZ-KRE"))
        self.choose_NBP_XML.setItemText(2, _translate("MainWindow", "MAZ-KRH"))
        self.choose_NBP_XML.setItemText(3, _translate("MainWindow", "MPZ-DEP"))
        self.choose_NBP_XML.setItemText(4, _translate("MainWindow", "MPZ-KRE"))
        self.choose_NBP_XML.setItemText(5, _translate("MainWindow", "MPZ-KRH"))
        self.choose_NBP_XML.setItemText(6, _translate("MainWindow", "MPZ-UDZ"))
        self.label_1.setText(_translate("MainWindow", "Choose XML"))
        self.label_2.setText(_translate("MainWindow", "Choose File"))
        self.label_3.setText(_translate("MainWindow", "Set sheet name"))
        self.NBP_SheetName.setPlainText(_translate("MainWindow", "Arkusz1"))
        self.NBP_CreateButton.setText(_translate("MainWindow", "Create"))
        
        # new
        self.GUS_XML_Form.setTitle(_translate("MainWindow", "Gus XMLs"))
        self.GUS_ChooseFile.setText(_translate("MainWindow", "Choose File"))
        self.choose_GUS_XML.setItemText(0, _translate("MainWindow", "C-01"))
        self.choose_GUS_XML.setItemText(1, _translate("MainWindow", "DG_1"))
        self.choose_GUS_XML.setItemText(2, _translate("MainWindow", "F-01"))
        self.choose_GUS_XML.setItemText(3, _translate("MainWindow", "MPZ-DEP"))
        self.choose_GUS_XML.setItemText(4, _translate("MainWindow", "MPZ-KRE"))
        self.choose_GUS_XML.setItemText(5, _translate("MainWindow", "MPZ-KRH"))
        self.choose_GUS_XML.setItemText(6, _translate("MainWindow", "SP"))
        self.label_1.setText(_translate("MainWindow", "Choose XML"))
        self.label_2.setText(_translate("MainWindow", "Choose File"))
        self.label_3.setText(_translate("MainWindow", "Set sheet name"))
        self.GUS_SheetName.setPlainText(_translate("MainWindow", "Arkusz1"))
        self.GUS_CreateButton.setText(_translate("MainWindow", "Create"))

        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.actionAdd_file.setIconText(_translate("MainWindow", "Add File"))
        self.actionAdd_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSort_Values.setText(_translate("MainWindow", "Sort Values in WB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())
